### PR TITLE
initial splash screen implemented.

### PR DESCRIPTION
**Pull request by bsdtux**
Hello I am attaching the change for my first commit. I am hoping to update this with actual buttons but figured this might be a good starting point

### CODE REVIEW

**Comment by bhansa** [comment]
@bsdtux sorry for the late reply, I tested your code and the only problem is it does not respond when we press `Q` or try to close the program. Can you try fixing that in next version?

**Comment by bsdtux** [comment]
thanks @bhansa. Can you give me more details about your environment. Running this on a Devuan machine and a Mac OS X machine I am not able to reproduce that issue. 

I also might have been confused on which screen we were talking about. Are you referring to the splash screen or are you referring to in the game?

**Comment by bhansa** [comment]
Okay, I just tested it again and it works fine may be the issue with my machine. Can we add any menu like bar with buttons on top anyhow? Please comment in the issue referencing to this. Thanks.

**Comment by bsdtux** [comment]
Sure. We can do that or I was thinking of just replacing the text with a couple of draw circles and adding the text play or quit and clicking on that will start the game or quit. I am open to which ever one you prefer.

**Comment by bhansa** [comment]
@bsdtux go with circles and both click and key shortcuts, it's open to you.

**Pull request merged**
